# simple Travis file to run style-checks until our internal CI can process external PRs

language: python
dist: xenial
sudo: false
python:
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.virtualenvs

addons:
  apt:
    packages:
      - graphviz

env:
  global:
    PROTOBUF_VERSION=3.6.1

install:
  - pip install --upgrade pip wheel setuptools
  - pip install poetry
  - poetry install
  # make sure poetry is installable without protobuf - install protoc later
  - curl -LO "https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip"
  - unzip "protoc-${PROTOBUF_VERSION}-linux-x86_64.zip" -d protoc
  - curl -LO "https://github.com/editorconfig-checker/editorconfig-checker/releases/download/2.2.0/ec-linux-amd64.tar.gz"
  - tar xfz ec-linux-amd64.tar.gz && mv bin/ec-linux-amd64 bin/editorconfig-checker
  - export PATH="$(pwd)/bin:$(pwd)/protoc/bin:$PATH"

script:
  - poetry run make style_check
  - poetry run make defs_check
  - poetry run make gen_check
  - poetry run make yaml_check
  - ci/check_fixup.sh

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
  on_success: always
  on_failure: always
  on_start: always
